### ISSUE TITLE
피드백 및 수요조사

### ISSUE THREAD

**Issue by llighter** [llighter/Acorn_Final#1]
- 이전 프로젝트에 대한 피드백
  - 보완점
  - 아쉬웠던 점
- 수요조사
  - 기술적 수요
  - 프로젝트 관리 수요
- 기타
  - 자유로운 의견 기술

> 공개의견은 아래 덧글로 작성하되 자세한 내용은 메일을 통해서 개별로 연락

**Comment by anyhuekil** [comment]
빡

**Comment by sinew8706** [comment]
빡이

**Comment by llighter** [comment]
이 이슈는 확인 하는 용도로 만 사용하고 구체적인 내용은 비공개로 메일을 통해 조사할 것입니다.
관련 메일은 발송했으니 확인바랍니다.

> 기한 엄수(9일 자정 까지)

**Comment by moneymashi** [comment]
ㅎㅇ

**Comment by llighter** [comment]
완료되었으므로 이슈를 닫음
